###
POST http://localhost:3000/user
Content-Type: application/json

{
  "name": "Oskars",
  "email": "ok2@gmail.com",
  "age": 32,
  "password": "123456",
  "repeatPassword": "123456"
}


###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "kkkk@gmail.com",
  "password": "123123"
}


###
GET http://localhost:3000/events?bands=alestorm

###
DELETE http://localhost:3000/events/ww

###
GET http://localhost:3000/events/alestorm-european-tour-2023

###
# @name login
GET http://localhost:3000/user/me
Cookie: token=<token>


###
@token = {{login.response.headers.Set-Cookie}}
POST http://localhost:3000/events
Content-Type: application/json
Cookie: {{token}}
# Content-Type: multipart/form-data

{
  "title": "Graspop 223",
  "category": "Music Festival",
  "bands": ["Dethklok", "Slipknot"],
  "city": "Desel",
  "location": "Field",
  "ticketPrice": 309,
  "date": "2025-06-19",
  "endDate": "2025-06-20"
}
