###
POST http://localhost:3000/user
Content-Type: application/json

{
  "name": "Oskars",
  "email": "ok1@gmail.com",
  "age": 32,
  "password": "123456"
}

###
POST http://localhost:3000/auth
Content-Type: application/json

{
  "email": "oskars@gmail.com",
  "password": "123456"
}


###
GET http://localhost:3000/events?bands=alestorm

###
DELETE http://localhost:3000/events/ww

###
GET http://localhost:3000/events/fest-the-tons-metal

###
POST http://localhost:3000/events
Content-Type: application/json
# Content-Type: multipart/form-data

{
  "title": "Graspop 2023",
  "category": "Music Festival",
  "bands": ["Dethklok", "Slipknot"],
  "city": "Desel",
  "location": "Field",
  "ticketPrice": 309,
  "date": "2025-06-19",
  "endDate": "2025-06-20"
}
